SELECT PRZEDMIOT.NAZWA, ROUND(AVG(OCENA.OCENA),2) AS "ŒREDNIA OCEN"  
FROM OCENA, PRZEDMIOT, ZAJECIA
WHERE ZAJECIA.ID_PRZEDMIOT=PRZEDMIOT.ID_PRZEDMIOT
AND ZAJECIA.ID_ZAJECIA=OCENA.ID_ZAJECIA
GROUP BY PRZEDMIOT.NAZWA;

SELECT
  WYKLADOWCA.IMIE||' '||WYKLADOWCA.NAZWISKO AS "WYKLADOWCA",
  PRZEDMIOT.NAZWA,
  BUDYNEK.NAZWA,
  SALA.KODSALI
FROM WYKLADOWCA, ZAJECIA, BUDYNEK, SALA, PRZEDMIOT
WHERE ZAJECIA.ID_WYKLADOWCA=WYKLADOWCA.ID_WYKLADOWCA
AND ZAJECIA.ID_SALA=SALA.ID_SALA
AND ZAJECIA.ID_PRZEDMIOT=PRZEDMIOT.ID_PRZEDMIOT
AND BUDYNEK.ID_BUDYNEK=SALA.ID_BUDYNEK;

SELECT 
  WYKLADOWCA.IMIE||' '||WYKLADOWCA.NAZWISKO AS "WYKLADOWCA",
  PRZEDMIOT.NAZWA,
  ROUND(AVG(OCENA.OCENA), 2) AS OCENA
FROM WYKLADOWCA, ZAJECIA, OCENA, PRZEDMIOT
WHERE 
  ZAJECIA.ID_WYKLADOWCA=WYKLADOWCA.ID_WYKLADOWCA
  AND ZAJECIA.ID_ZAJECIA=OCENA.ID_ZAJECIA
  AND ZAJECIA.ID_PRZEDMIOT=PRZEDMIOT.ID_PRZEDMIOT
GROUP BY PRZEDMIOT.NAZWA, WYKLADOWCA.IMIE||' '||WYKLADOWCA.NAZWISKO;

--mozna bez podzapytania
--SKONCZYC
--ZAD4
SELECT 
  PRZEDMIOT.NAZWA AS PRZEDMIOT, 
  WYKLADOWCA.IMIE||' '||WYKLADOWCA.NAZWISKO AS "WYKLADOWCA",
  COUNT
  (
    SELECT STUDENT.ID_STUDENT
    FROM STUDENT, OCENA, PRZEDMIOT
    WHERE
      ZAJECIA.ID_PRZEDMIOT=PRZEDMIOT.ID_PRZEDMIOT
      AND PRZEDMIOT.ID_PRZEDMIOT=P.ID_PRZEDMIOT
      AND STUDENT.ID_GRUPA=ZAJECIA.ID_GRUPA
      AND STUDENT.ID_STUDENT=OCENA.ID_STUDENT
      AND OCENA.OCENA<3;  
  ) AS LICZBA_NIEZALICZONYCH
FROM PRZEDMIOT P, STUDENT, WYKLADOWCA, ZAJECIA
WHERE 
  ZAJECIA.ID_PRZEDMIOT=PRZEDMIOT.ID_PRZEDMIOT
  AND ZAJECIA.ID_WYKLADOWCA=WYKLADOWCA.ID_WYKLADOWCA
  AND PRZEDMIOT.ID_PRZEDMIOT=ZAJECIA.ID_PRZEDMIOT
GROUP BY PRZEDMIOT, LICZBA_NIEZALICZONYCH
ORDER BY LICZBA_NIEZALICZONYCH;

--ZAD5
SELECT 
  WYKLADOWCA.IMIE, 
  WYKLADOWCA.NAZWISKO,
  COUNT(ZAJECIA.ID_PRZEDMIOT) AS LICZBA_PRZEDMIOTOW
FROM WYKLADOWCA, ZAJECIA, PRZEDMIOT
WHERE 
  WYKLADOWCA.ID_WYKLADOWCA=ZAJECIA.ID_WYKLADOWCA
  AND PRZEDMIOT.ID_PRZEDMIOT=ZAJECIA.ID_PRZEDMIOT
GROUP BY WYKLADOWCA.IMIE, WYKLADOWCA.NAZWISKO
ORDER BY LICZBA_PRZEDMIOTOW DESC
FETCH FIRST ROW ONLY;

--ZAD5 2 SPOSOB Z PODZAPYTANIEM

--ZAD6
SELECT 
  STUDENT.IMIE, 
  STUDENT.NAZWISKO, 
  GRUPA.NAZWA, 
  KIERUNEK.NAZWA
